language: go
go:
- 1.11.x
- 1.12.x
script:
- go test -v ./...
jobs:
  include:
  - stage: deploy
    deploy:
      provider: script
      skip_cleanup: true
      script: sh -c 'npm install && npx semantic-release'
env:
  global:
    - GO111MODULE=on
    - secure: TEZb+dU7m5dmLEQLSQSiC4/IuLAK5YGQX0YSfAbFpf/rGxDZJe6TUe68IULAu0tzan5omAwQGLwBdcBVo9fsVLoiEd/xkljSjXPBwiQ93UnuBnrjoFu2099+U0YMF2Mopg1iGhtUF+VqEV094f0vl4ICmv1Zo7DWJWRdbwPnaDJvZrvVtx4X1FKA4x7zRvpsDOvTil8R87RZ62G49WNqutfBWBduMsospC0eP9TlAG0V6vZslAgCSBKCOGYzMMaHC3F2GdFSURw4uLaAsXqK8/u9Hj0Fp47M6cHL06QJrVN2ioGff30KC35u/B1jukZITZ1pVZmHKagJCBnDyPCqkyexJ+ggDdmIacooXjQAhW8xdbze7p4RioSfMCt9lDzlAb+J677uVSkIU2XeY6kg8H2dvN+hoYFmogkGff4bAhOBdQY/0QaETXEWjczxdSBf8AD/I/llwMtQQj0LGg9ddzFgTPLVIon8Tsh/ZuXdg0sH6wZzSeXyyEoI2Z6IX3+FpH88BZMK6GhKzqjbq3uqAgoTuqoTP0oTAcHA12N+9j+FZxe8D4T9qqVzGn4c5FFdHIdFF4oFJ5N+5L+lgsgnG4XP85QPd3s2kvKvGAGfMSmhej+6Pp60Dia3WnchB7cLbgVkkBywuc15nZfMOKNCa6A37YqnakPPSGU33E+gkYA=
